---
- name: Get puppet facts
  getpuppetdbfacts:
    puppetdb_url: https://puppetmaster5.sherwin.com:8081/pdb/query/v4/inventory
    cert_file: '{{puppetdb_public}}'
    pkey_file: '{{puppetdb_private}}'
    query_by: 'facts.hostname'
    query_equals: "{{inventory_hostname.split('.')[0]}}"
    validate_certs: no
  register: puppetfact
  ignore_errors: true
  delegate_to: 127.0.0.1

- name: Server not in Puppet
  block:
    - name: Deduct 10 points (Puppet missing)
      set_fact:
        score: "{{ score|int - 10 }}"
    - name: Update server summary (Puppet missing)
      set_fact:
        wmsummary: "{{ wmsummary }} PUPPET: Server is missing from Puppet. [-10]|"
  when: (puppetfact.failed is defined and puppetfact.failed) or puppetfact is not defined
  delegate_to: 127.0.0.1
  become: false

- name: Server running in no-op
  block:
    - name: Deduct 5 points (Puppet no-op)
      set_fact:
        score: "{{ score|int - 5 }}"
    - name: Update server summary (Puppet noop)
      set_fact:
        wmsummary: "{{ wmsummary }} PUPPET: Server is running in no-op mode. [-5]|"
  when:  puppetfact['output'][0]['facts'] is defined and puppetfact['output'][0]['facts']['clientnoop'] is defined and puppetfact['output'][0]['facts']['clientnoop']
  delegate_to: 127.0.0.1
  become: false

- name: Server snowflake
  block:
    - name: Deduct 15 points (Puppet snowflake)
      set_fact:
        score: "{{ score|int - 15 }}"
    - name: Update server summary (Puppet snowflake)
      set_fact:
        wmsummary: "{{ wmsummary }} PUPPET: Server is marked as a snowflake custom_admin_org. [-15]|"
  when:  puppetfact['output'][0]['facts']['custom_admin_org'] is defined and puppetfact['output'][0]['facts']['custom_admin_org']=="snowflake"
  delegate_to: 127.0.0.1
  become: false

- name: Qualys facts missing
  block:
    - name: Deduct 10 points (Qualys facts)
      set_fact:
        score: "{{ score|int - 10 }}"
    - name: Update server summary (Qualys facts)
      set_fact:
        wmsummary: "{{ wmsummary }} QUALYS: Qualys has not logged in. [-10]|"
  when:  puppetfact['output'][0]['facts'] is defined and puppetfact['output'][0]['facts']['custom_last_qualys'] is not defined and puppetfact['output'][0]['facts']['custom_last_qualys_fq'] is not defined and puppetfact['output'][0]['facts']['custom_last_qualys_dmz'] is not defined
  delegate_to: 127.0.0.1
  become: false

- name: AD auth check
  block:
    - name: Deduct 10 points (AD auth)
      set_fact:
        score: "{{ score|int - 10 }}"
    - name: Update server summary (AD auth)
      set_fact:
        wmsummary: "{{ wmsummary }} AD AUTH: no valid AD processes found. [-10]|"
  when:  puppetfact['output'][0]['facts'] is defined and (puppetfact['output'][0]['facts']['custom_winbindd_running'] == "false" and puppetfact['output'][0]['facts']['custom_sssd_running'] == "false")
  delegate_to: 127.0.0.1
  become: false

- name: Puppet is applying resources
  block:
    - name: Deduct 5 points (Puppet failing)
      set_fact:
        score: "{{ score|int - 5 }}"
    - name: Update server summary (Puppet failing)
      set_fact:
        wmsummary: "{{ wmsummary }} PUPPET: Puppet is failing to apply resources. [-5]|"
  when:  puppetfact['output'][0]['facts'] is defined and puppetfact['output'][0]['facts']['resources']['failed'] is defined and (puppetfact['output'][0]['facts']['resources']['failed'] != 0)
  delegate_to: 127.0.0.1
  become: false

- name: Server is beyond 90 days since last Qualys login
  block:
    - name: Deduct 10 points (Qualys 90 days)
      set_fact:
        score:  "{{ score|int - 10 }}"
    - name: Update server summary (Qualys 90 days)
      set_fact:
        wmsummary: "{{ wmsummary }} QUALYS: Server is beyond 90 days from last login from qualys user. [-10]|"
  when: (puppetfact['output'][0]['facts']['custom_last_qualys'] is defined and "20" in puppetfact['output'][0]['facts']['custom_last_qualys'] and (current_date.stdout |to_datetime -  puppetfact['output'][0]['facts']['custom_last_qualys']| to_datetime('%b %d %Y')).days > 90) or (puppetfact['output'][0]['facts']['custom_last_qualys_fq'] is defined and "20" in puppetfact['output'][0]['facts']['custom_last_qualys_fq'] and (current_date.stdout |to_datetime -  puppetfact['output'][0]['facts']['custom_last_qualys_fq']| to_datetime('%b %d %Y')).days > 90) or (puppetfact['output'][0]['facts']['custom_last_qualys_dmz'] is defined and "20" in puppetfact['output'][0]['facts']['custom_last_qualys_dmz'] and (current_date.stdout |to_datetime -  puppetfact['output'][0]['facts']['custom_last_qualys_dmz']| to_datetime('%b %d %Y')).days > 90)
  delegate_to: 127.0.0.1
  become: false


- name: Server is beyond 90 days since last SOX check
  block:
    - name: Deduct 10 points (SOX 90 days)
      set_fact:
        score:  "{{ score|int - 10 }}"
    - name: Update server summary (SOX 90 days)
      set_fact:
        wmsummary: "{{ wmsummary }} SOX: Server is beyond 90 days from last run. [-10]|"
  when: puppetfact['output'][0]['facts']['custom_sox_rundate'] is defined and puppetfact['output'][0]['facts']['custom_sox_rundate'] | length > 2  and (current_date.stdout |to_datetime -  puppetfact['output'][0]['facts']['custom_sox_rundate'].replace(puppetfact['output'][0]['facts']['custom_sox_rundate'].split(" ")[4],'')| to_datetime('%a %b %d %H:%M:%S %Y')).days > 90
  delegate_to: 127.0.0.1
  become: false


# yikes.
# if there's a better way, please do a pull request
- name: SOX Errors
  block:
    - name: Deduct 10 points (SOX errors)
      set_fact:
        score: "{{ score|int - 10 }}"
    - name: Update server summary (SOX errors)
      set_fact:
        wmsummary: "{{ wmsummary }} SOX: SOX report facts missing or failing. sox_ma05c={{ puppetfact['output'][0]['facts']['custom_sox_ma05c'] | default('sox_ma05c missing')}} sox_ma02b={{ puppetfact['output'][0]['facts']['custom_sox_ma02b'] | default('sox_ma02b missing')}} sox_ma02a={{ puppetfact['output'][0]['facts']['custom_sox_ma02a'] | default('sox_ma02a missing')}} sox_ma01e={{ puppetfact['output'][0]['facts']['custom_sox_ma01e'] | default('sox_ma01e missing')}} sox_ma01d={{ puppetfact['output'][0]['facts']['custom_sox_ma01d'] | default('sox_ma01d missing')}} sox_ma01c={{ puppetfact['output'][0]['facts']['custom_sox_ma01c'] | default('sox_ma01c missing')}} sox_ma01b={{ puppetfact['output'][0]['facts']['custom_sox_ma01b'] | default('sox_ma01b missing')}} sox_ma01a={{ puppetfact['output'][0]['facts']['custom_sox_ma01a'] | default('sox_ma01a missing')}} [-10]|"
  when: puppetfact['output'][0]['facts'] is defined and ((puppetfact['output'][0]['facts']['custom_sox_ma05c'] is not defined or puppetfact['output'][0]['facts']['custom_sox_ma05c']!="0") or ('custom_sox_ma02b' not in puppetfact['output'][0]['facts'] or puppetfact['output'][0]['facts']['custom_sox_ma02b']!="0") or ('custom_sox_ma02a' not in puppetfact['output'][0]['facts'] or puppetfact['output'][0]['facts']['custom_sox_ma02a']!="0") or ('custom_sox_ma01e' not in puppetfact['output'][0]['facts'] or puppetfact['output'][0]['facts']['custom_sox_ma01e']!="0") or ('custom_sox_ma01d' not in puppetfact['output'][0]['facts'] or puppetfact['output'][0]['facts']['custom_sox_ma01d']!="0") or ('custom_sox_ma01c' not in puppetfact['output'][0]['facts'] or puppetfact['output'][0]['facts']['custom_sox_ma01c']!="0") or ('custom_sox_ma01b' not in puppetfact['output'][0]['facts'] or puppetfact['output'][0]['facts']['custom_sox_ma01b']!="0") or ('custom_sox_ma01a' not in puppetfact['output'][0]['facts'] or puppetfact['output'][0]['facts']['custom_sox_ma01a']!="0"))
  delegate_to: 127.0.0.1
  become: false

- name: SOX Penalty for missing puppet
  block:
    - name: Deduct 10 points (SOX errors)
      set_fact:
        score: "{{ score|int - 10 }}"
    - name: Update server summary (SOX puppet penalty)
      set_fact:
        wmsummary: "{{ wmsummary }} SOX: Cannot retrieve SOX facts [-10].|"
  when: puppetfact['output'][0]['facts'] is not defined

